name: cron-2021.8-core-ubuntu-latest

env:
  os: ubuntu-latest
  distro: core
  epoch: '2021.8'

on:
  pull_request: {}
#  schedule:
#    # evey 4 hrs
#    - cron: '0 */4 * * *'

jobs:
  install_env:
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.collect_urls.outputs.urls }}
      metapackage_spec: ${{ steps.metapackage.outputs.spec }}
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: configure conda and friends
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          conda config --set always_yes yes
          conda config --set changeps1 no
          conda config --set quiet true
          sudo conda upgrade -n base -q -y -c defaults --override-channels conda
          sudo conda install -n base -q -y -c defaults --override-channels conda-build yq
          conda info -a
          conda config --show

      - name: identify metapackage
        id: metapackage
        env:
          DATA_FILE:  ${{ env.epoch }}/staged/${{ env.distro }}/data.yaml
          META_FILE: ${{ env.epoch }}/staged/${{ env.distro }}/meta.yaml.jinja
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          echo "::set-output name=spec::$(head -n 2 $META_FILE | yq -r .package.name)=$(yq -r .version $DATA_FILE)"

      - name: install metapackage
        env:
          Q2_CHANNEL:  https://packages.qiime2.org/qiime2/${{ env.epoch }}/staged/${{ env.distro }}
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          sudo conda create -q -n test-env -c $Q2_CHANNEL -c conda-forge -c bioconda -c defaults ${{ steps.metapackage.outputs.spec }}
          sudo conda run -n test-env python -c 'import qiime2'

      - name: collect tar.bz2's
        id: collect_urls
        env:
          DATA_FILE:  ${{ env.epoch }}/staged/${{ env.distro }}/data.yaml
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate test-env
          urls=$(jq -cs '[ .[0].run[] as $packages | .[1][] | select(.name | IN($packages)) | .base_url + "/" + .platform + "/" + .dist_name + ".tar.bz2"]' \
                  <(conda run -n base yq -cj '.' $DATA_FILE) \
                  <(conda list --json))
          echo "::set-output name=urls::$urls"

  test_package:
    needs: install_env
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url: ${{ fromJson(needs.install_env.outputs.urls) }}
    steps:
      - name: configure conda and friends
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          conda config --set always_yes yes
          conda config --set changeps1 no
          conda config --set quiet true
          sudo conda upgrade -n base -q -y -c defaults --override-channels conda
          sudo conda install -n base -q -y -c defaults --override-channels conda-build
          conda info -a
          conda config --show

      - name: run test
        env:
          Q2_CHANNEL:  https://packages.qiime2.org/qiime2/${{ env.epoch }}/staged/${{ env.distro }}
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda activate base
          wget ${{ matrix.url }}
          sudo conda build -q -c $Q2_CHANNEL -c conda-forge -c bioconda -c defaults --extra-deps ${{ needs.install_env.outputs.metapackage_spec }} -t "*.tar.bz2"
