name: cron

on:
  schedule:
    # evey 4 hrs
    - cron: '0 */4 * * *'

jobs:
  integrate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        distro:
          - core
        epoch:
          - '2021.8'
    env:
      BUILD_DIR: ./build/
      TEMPLATE_PATH: ${{ matrix.epoch }}/staged/${{ matrix.distro }}/
      Q2_CHANNEL: https://packages.qiime2.org/qiime2/${{ matrix.epoch }}/tested/
    steps:
      - name: set host helper env vars
        run: |
          case "${{ matrix.os }}" in
            'ubuntu-latest') echo 'PLATFORM=linux' >> $GITHUB_ENV ;;
            'macos-latest') echo 'PLATFORM=osx' >> $GITHUB_ENV ;;
          esac

      - name: checkout source
        uses: actions/checkout@v2

      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install 'jinja2<3' pyyaml

      - name: template recipe
        run: python .github/workflows/bin/template.py $TEMPLATE_PATH --tests

      - name: debug recipe
        run: cat $TEMPLATE_PATH/meta.yaml

      - name: configure conda
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          conda config --set always_yes yes --set changeps1 no
          sudo conda upgrade -n base -q -y -c defaults --override-channels conda
          sudo conda install -n base -q -y -c defaults --override-channels conda-build conda-verify
          conda info -a

      - name: build recipe
        run: |
          sudo conda build \
            -c $Q2_CHANNEL \
            -c conda-forge \
            -c bioconda \
            -c defaults \
            --override-channels \
            --output-folder $BUILD_DIR \
            --no-anaconda-upload \
            $TEMPLATE_PATH
